# Generated by Django 5.2.13 on 2026-09-17 14:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_professional_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantDirectRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Matrix account"
                    ),
                ),
                (
                    "room_id",
                    models.CharField(max_length=255, verbose_name="Matrix room"),
                ),
            ],
            options={
                "verbose_name": "assistant direct room",
                "verbose_name_plural": "assistant direct rooms",
                "db_table": "hub_assistant_direct_room",
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="closed_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="scheduled_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="started_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="url",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="call link"
            ),
        ),
    ]
