# Generated by Django 5.2.13 on 2026-09-17 16:22

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_meeting_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="board_elements",
            field=models.JSONField(blank=True, null=True, verbose_name="whiteboard"),
        ),
        migrations.AddField(
            model_name="meetingattachment",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=500,
                upload_to=core.models.meeting_attachment_path,
                verbose_name="file",
            ),
        ),
        migrations.AddField(
            model_name="meetingattachment",
            name="size",
            field=models.PositiveBigIntegerField(default=0, verbose_name="size"),
        ),
        migrations.AlterField(
            model_name="meetingattachment",
            name="content",
            field=models.TextField(blank=True, verbose_name="content"),
        ),
    ]
