# Generated by Django 5.2.13 on 2026-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_meeting_documents_and_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="space_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="espace"),
        ),
    ]
