# Generated by Django 5.2.13 on 2026-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_meeting_space_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="space_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="space"),
        ),
    ]
