# Generated by Django 5.2.13 on 2026-09-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_meeting_space_name_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingchatmessage",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the scribe said it posted an assistant message.",
                null=True,
                verbose_name="delivered on",
            ),
        ),
    ]
