# Generated by Django 5.2.13 on 2026-09-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_meeting_chat_message_delivered_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingchatmessage",
            name="aside",
            field=models.BooleanField(
                default=False,
                help_text="An assistant message that is no answer (help, failure): it is not read back to her as part of the conversation.",
                verbose_name="aside",
            ),
        ),
    ]
